import { AiFillStar } from "react-icons/ai";
import React, { useState } from "react";
const data = [
  
  {
    img: "https://m.media-amazon.com/images/I/410F2yAQlxL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Women's Solid Crop Top",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹400",
    newPrice: "350",
    company: "Nike",
    color: "blue",
    category: "Tops",
  
  },
  {
    img: "https://i.pinimg.com/236x/18/82/b5/1882b5aacd7c92b4a92824515be3d74a.jpg",
    title:"Women's Regular Fit Solid Sleeveless Crop Top",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹800",
    newPrice: "350",
    company: "Nike",
    color: "black",
    category: "Tops",
  },
  {
    img: "https://m.media-amazon.com/images/I/81oLjXjVXmL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Crop Tops for Women",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹800",
    newPrice: "429",
    company: "Roadster",
    color: "White",
    category: "Tops",
  },

  {
    img: "https://i.pinimg.com/236x/e7/98/57/e798574654572d57a4305a1e46140737.jpg",
    title: "Nike Womens Top",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹400",
    newPrice: "349",
    company: "Nike",
    color: "silver",
    category: "Tops",
  },
  {
    img: "https://i.pinimg.com/236x/4f/4a/db/4f4adba87c1274c531ce6e74d3b62a87.jpg",
    title: "Nike Womens Crop Top",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹800",
    newPrice: "429",
    company: "Roadster",
    color: "black",
    category: "Tops",
  },
  {
    img: "https://m.media-amazon.com/images/I/81gVKUkQLqL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Women Regular Fit Top",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹400",
    newPrice: "350",
    company: "Illi London",
    color: "pink",
    category: "Tops",
  },
  {
    img: "https://m.media-amazon.com/images/I/71h9ZzXY93L._AC_UL480_FMwebp_QL65_.jpg",
    title: "Knit Ballet Top",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹800",
    newPrice: "429",
    company: "Roadster",
    color: "black",
    category: "Tops",
  },

  {
    img: "https://m.media-amazon.com/images/I/61+5odVyMIL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Classic Womens Top",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹400",
    newPrice: "329",
    company: "Illi London",
    color: "orange",
    category: "Tops",
  },

  {
    img: "https://m.media-amazon.com/images/I/61IpZsXyMjL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Pink Off Shoulder Crop top",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹800",
    newPrice: "429",
    company: "Nike",
    color: "pink",
    category: "Tops",
  },

  {
    img: "https://m.media-amazon.com/images/I/61TcF3yftCL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Women's Printed Regular Fit top",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹400",
    newPrice: "359",
    company: "Roadster",
    color: "pink",
    category: "Tops",
  },

  {
    img: "https://m.media-amazon.com/images/I/31LwjS72IML._AC_UL480_FMwebp_QL65_.jpg",
    title: "Womens Latest Cotton Ribbed Full Sleeves Zip Top ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹400",
    newPrice: "229",
    company: "Uptownie",
    color: "brown",
    category: "Tops",
  },

  {
  img: "https://m.media-amazon.com/images/I/51tzz6Ib+PL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Women's & Girls' Solid Side Split Hem Flare Leg Bell Bottoms",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹800",
    newPrice: "429",
    company: "Uptownie",
    color: "black",
    category: "Bottoms",
  },

  {   
      img: "https://m.media-amazon.com/images/I/61L8uzPM-xL._AC_UL480_FMwebp_QL65_.jpg",
      title: "Women's Comfort Fit Cotton Blend Jogger Pants",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "₹400",
      newPrice: "299",
      company: "Uptownie",
      color: "green",
      category: "Bottoms",
  },

  {
      img: "https://m.media-amazon.com/images/I/61r+ZK+jPtL._AC_UL480_FMwebp_QL65_.jpg",
      title: "Pacer Future Stylish Pants",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "₹800",
      newPrice: "429",
      company: "Uptownie",
      color: "black",
      category: "Bottoms",
  },

  {
      img: "https://m.media-amazon.com/images/I/61scRIy1ePL._AC_UL480_QL65_.jpg",
      title: "Women's Slim Fit Casual Trousers",
      star: <AiFillStar className="rating-star" />,
      reviews: "(123 reviews)",
      prevPrice: "₹600",
      newPrice: "429",
      company: "Uptownie",
      color: "black",
      category: "Bottoms",
   },

  {
    img: "https://m.media-amazon.com/images/I/61dcVrW8ipL._AC_UL480_QL65_.jpg",
    title: "Gym wear Leggings Workout Pants ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹459",
    newPrice: "429",
    company: "Uptownie",
    color: "red",
    category: "Bottoms",
    
  },
  
  {
    img: "https://m.media-amazon.com/images/I/61+4lyADxlL._AC_UL480_QL65_.jpg",
    title: "Wide Leg Jeans Women",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹600",
    newPrice: "429",
    company: "Uptownie",
    color: "blue",
    category: "Bottoms",
  },

  {
    img: "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
    title: "Unisex-Adult Super",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹459",
    newPrice: "429",
    company: "Uptownie",
    color: "black",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg",
    title: "Roma Basic Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹600",
    newPrice: "429",
    company: "Uptownie",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg",
    title: "Pacer Future Doubleknit",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹459",
    newPrice: "429",
    company: "Uptownie",
    color: "black",
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    title: "Fusion Evo Golf Shoe",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹600",
    newPrice: "100",
    company: "Uptownie",
    color: "green",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/719gdz8lsTS._AC_UX575_.jpg",
    title: "Rainbow Chex Skate",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹459",
    newPrice: "429",
    company: "Illi London",
    color: "red",
    category: "flats",
  },
  {
    img: "https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg",
    title: "Low-Top Trainers",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹600",
    newPrice: "100",
    company: "Illi London",
    color: "white",
    category: "sandals",
  },
  {
    img: "https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg",
    title: "Illi London Unisex Low-Top",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹459",
    newPrice: "429",
    company: "Illi London",
    color: "blue",
    category: "sandals",
  },
  {
    img: "https://m.media-amazon.com/images/I/61N4GyWcHPL._AC_UY575_.jpg",
    title: "Classic Bandana Sneakers",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹600",
    newPrice: "429",
    company: "Nike",
    color: "black",
    category: "sandals",
  },
  {
    img: "https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg",
    title: "Chunky High Heel",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹459",
    newPrice: "429",
    company: "Illi London",
    color: "black",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/71czu7WgGuL._AC_UY695_.jpg",
    title: "Slip On Stiletto High Heel",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹600",
    newPrice: "300",
    company: "Uptownie",
    color: "black",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
    title: "DREAM PAIRS Court Shoes",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹459",
    newPrice: "429",
    company: "Nike",
    color: "red",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    title: "Nike Air Vapormax Plus",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹600",
    newPrice: "329",
    company: "Nike",
    color: "red",
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg",
    title: "Low Mid Block Heels",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹459",
    newPrice: "390",
    company: "Nike",
    color: "black",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/616sA5XUKtL._AC_UY675_.jpg",
    title: "Chunky High Heel",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹600",
    newPrice: "429",
    company: "Roadster",
    color: "black",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg",
    title: "Amore Fashion Stilettos",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹459",
    newPrice: "429",
    company: "Roadster",
    color: "white",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/61uw5RDxKQL._AC_UY625_.jpg",
    title: "Bridal Sandals Glitter",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹600",
    newPrice: "429",
    company: "Roadster",
    color: "black",
    category: "heels",
  },
  
  {
    img: "https://m.media-amazon.com/images/I/61GIXALQxzL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Women's Hoodies || Sweatshirt for Women ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹459",
    newPrice: "349",
    company: "Roadster",
    color: "blue",
    category: "Sweaters",
  },
  {
    img: "https://m.media-amazon.com/images/I/613nqYNgh6L._AC_UL480_FMwebp_QL65_.jpg",
    title: "Women Full Sleeve Solid Hooded Sweatshirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹600",
    newPrice: "429",
    company: "Roadster",
    color: "orange",
    category: "Sweaters",
  },
  {
    img: "https://m.media-amazon.com/images/I/512NuTjNQ+L._AC_UL480_FMwebp_QL65_.jpg",
    title: "Winter Wear Sweatshirt Hooded Neck Regular Fit ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹459",
    newPrice: "429",
    company: "Roadster",
    color: "pink",
    category: "Sweaters",
  },
  {
    img: "https://m.media-amazon.com/images/I/51nleFl487L._AC_UL480_FMwebp_QL65_.jpg",
    title: "Women's Boyfriend/Loose Fit Hooded Neck Sweatshirt ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹600",
    newPrice: "429",
    company: "Roadster",
    color: "black",
    category: "Sweaters",
  },
  {
    img: "https://m.media-amazon.com/images/I/61yjZNe0HGL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Cotton Poly Fleece Official Disney Merchandise Regular Fit",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹600",
    newPrice: "34",
    company: "Roadster",
    color: "orange",
    category: "Sweaters",
  },
  {
    img: "https://m.media-amazon.com/images/I/61aklx2UlXL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Oversize Baggy Hoodie",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹459",
    newPrice: "24",
    company: "Roadster",
    color: "red",
    category: "Sweaters",
  },
  {
    img: "https://m.media-amazon.com/images/I/71rmM69WmmL._SY679_.jpg",
    title: "Sweatshirt for Unisex || Unisex Hoodie",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹600",
    newPrice: "29",
    company: "Roadster",
    color: "black",
    category: "Sweaters",
  },
];


export default data;